### ISSUE TITLE
billing address not stored with customer/invoice

### ISSUE THREAD

**Issue by sehmaschine** [stripe-samples/checkout-single-subscription#12]
I'm using the client-server code with python and added `billing_address_collection="required",` to the server-side create checkout session code. With the payment form, the billing address is shown, but it is not stored with neither the customer nor the invoice.

**Comment by cjavilla-stripe** [comment]
Sorry for the delayed response! The billing address will be on the PaymentMethod attached to the Customer.

**Comment by Phmager** [comment]
@cjavilla-stripe Hi, sorry to open the topic up again, but this leads to big issues.
The invoice created from a subscription through checkout does not contain the customer address. I think the reason is, that the customer created by stripe checkout does not have the billing address set, but only contains it on the PaymentMethod.

Do you have any proposal on how to fix it?

**Comment by cjavilla-stripe** [comment]
One option is to update the customer when you receive the checkout.session.completed event.

**Comment by Phmager** [comment]
Thanks for the very fast answer, after looking through available events, I will try to do it this way:

```csharp
if (stripeEvent.Type == Events.PaymentMethodAttached)
                {
                    var element = stripeEvent.Data.Object as Stripe.PaymentMethod;
                    
                    var service = new CustomerService();
                    var customer = await service.GetAsync(element.CustomerId);
                    if (customer.Address == null)
                    {
                        var address = element.BillingDetails.Address;
                        await service.UpdateAsync(element.CustomerId, new CustomerUpdateOptions()
                        {
                            Address = new AddressOptions()
                            {
                                City = address.City,
                                State = address.State,
                                Country = address.Country,
                                Line1 = address.Line1,
                                Line2 = address.Line2,
                                PostalCode = address.PostalCode
                            }
                        });
                    }
                }
``` 

So when the first payment method is attached, I will apply the address to the customer.
Only question is if I'm fast enough, so that the update is done before the invoice is created and sent to the user. I just hope so and will need to check in Live-Mode, as in Dev Mode the email is not created.

**Comment by cjavilla-stripe** [comment]
Thanks for the update, @Phmager. Happy to hear this solution works for you.
