### ISSUE TITLE
Using stripe samples and client-server means you need to change the STATIC_DIR

### ISSUE THREAD

**Issue by eb379** [stripe-samples/checkout-single-subscription#17]
When using the `stripe samples` command to clone the repository, it removes the `python/` folder (and copies the content into 'server'). This then means that when you run the application, it is unable to find the client files because the static dir is set to `../../client` while it should be set to `../client`.

Potential solutions:
- Ensure the stripe samples command also edits the `.env.example` file to set the static director appropriately
OR
- Update the documentation to make clear that the static dir should be updated.

**Comment by thorsten-stripe** [comment]
When you're logged in (`stripe login`) the stripe cli will automatically generate the `.env` file for you and set `STATIC_DIR="../client"`.

**Comment by eb379** [comment]
That's pretty opaque from the documentation -- it would be good to indicate you need to do stripe login before stripe samples create if that's the case...

**Comment by thorsten-stripe** [comment]
@eb379 thanks, that's very fair feedback, since the CLI is changing paths it should also set up the `.env` file even when not logged in. Currently it only outputs: 
![image](https://user-images.githubusercontent.com/23213994/87324021-1cde0280-c562-11ea-88e7-367598a6ef16.png)

I've opened an issue for this here: https://github.com/stripe/stripe-cli/issues/483

Thanks for flagging! :)
