### ISSUE TITLE
Repeat Orders

### ISSUE THREAD

**Issue by mikeumus** [stripe-samples/checkout-single-subscription#89]
Every night, 3 or so orders repeat. Any idea how this could be happening? 

<img width="1409" alt="Screen Shot 2021-07-07 at 4 55 57 PM" src="https://user-images.githubusercontent.com/57934/124827581-34b55000-df44-11eb-88b4-2a8f6cf48da6.png">

**Comment by cjavdev** [comment]
Are these part of a test suite?

**Comment by mikeumus** [comment]
@cjavdev yeah, test-mode.

**Comment by cjavilla-stripe** [comment]
Sorry, to be clear. Is it possible those repeat orders are the result of running a test suite as part of continuous integration or similar?

**Comment by mikeumus** [comment]
@cjavdev no I don't have any testing on this checkout server yet. I had the server running via `systemctl` and thought that might be it somehow but I tested that idea last night and still got the three orders by just running the server with `go run server.go` directly.

**Comment by cjavilla-stripe** [comment]
Okay. I recommend looking into the request [logs](https://dashboard.stripe.com/test/logs?method[]=post&method[]=delete&direction[]=connect_in&direction[]=self) in your Stripe dashboard and trying to determine where the requests are coming from. Take a look at the IP address and Source to see if there are any hints. 

Otherwise, I'd recommend chatting with us on [Discord](https://stripe.com/go/developer-chat) if you have further questions.
