### ISSUE TITLE
Discrepancy between GitHub code and live-demo code — intentional?

### ISSUE THREAD

**Issue by ultraGentle** [stripe-samples/checkout-single-subscription#9]
Hello, I'm working through the client-only integration, and noticed a discrepancy between the live demo, at https://4iupj.sse.codesandbox.io/ , and the GitHub repo.  

If you inspect the live demo in browser devtools, there's an extra code block, which results in the session information being displayed on the 'success' page (copied at the bottom).  

That `fetch` path doesn't exist in the sample or on my own page.  Am I correct in assuming that
1. it's just there to demo what the `session` returns?  And, 
2. Checkout does not generate/provide such a path that I would be able to access?  I.e., is this just a path or route you guys made on your own server for the purposes of the demo?  

I'm getting all the necessary logs and session info in my own server side code via a Webhook, but I wanted to make sure that I'm not missing a more direct way to acquire the session info on the client side.  

**Discrepant Code**
```
var sessionId = urlParams.get("session_id")
if (sessionId) {
   fetch("/checkout-session?sessionId=" + sessionId).then(function (result) {
          return result.text();
        }).then(function (session) {
          var sessionJSON = JSON.stringify(session, null, 2);
          document.querySelector("#stripejson").textContent = sessionJSON;
        })
      }
```

Thanks!

**Comment by adreyfus-stripe** [comment]
@ultraGentle Thanks for reporting! Our live demo is actually of the client-and-server integration which is why you see the discrepancies. I updated the demo and README to make this clearer. 

If you wanted to get the resulting CheckoutSession after the checkout is complete, you would need to have a server to fetch the object (https://stripe.com/docs/api/checkout/sessions/retrieve) 

For the client-only solution your best plan would be to have a simple static "Thank you for your purchase!" page if you do not want a server to look up the details of the CheckoutSession. 

Hope that helps!
